### ISSUE TITLE
我遇到的一些培训机构

### ISSUE THREAD

**Issue by easepan** [ZGWS88/TI#10]
公司：北京华清远见科技发展有限公司成都分公司
地址：成都市武侯区科华北路99号科华大厦

公司：四川百年有为教育咨询有限公司
地址：成都市天府新谷8栋2单元9楼

公司：成都白起网络科技有限公司
地址：成都市天府新谷8栋2单元9楼

公司：四川金明科技发展有限公司
地址：成都市天府新谷8栋2单元9楼

公司：四川育道科技有限公司
地址：成都高新区天府四街199号（长虹科技大厦B座）

**Comment by npcola** [comment]
谢谢，已添加。
（辛苦了
