### ISSUE TITLE
深圳市灵沃软件开发有限公司

### ISSUE THREAD

**Issue by starlight02** [ZGWS88/TI#11]
地址：深圳市南山区粤海街道科技中二路麻雀岭工业区M-2栋5楼B21

**Comment by starlight02** [comment]
深圳市星诚软件开发有限公司
地址：深圳市南山区粤海街道大冲新城花园2A栋

**Comment by starlight02** [comment]
深圳市星诚软件开发有限公司
地址：深圳市南山区粤海街道科发路6号康泰生物2栋303

**Comment by starlight02** [comment]
深圳市志远弘业网络科技有限公司
地址：深圳市南山区粤海街道高新南四道高新技术工业村R1-A栋附3楼

深圳市华里夫服饰有限公司
地址：深圳市南山区粤海街道高新南四道高新技术工业村R1-A栋附3楼301

深圳市歌佰芬服装有限公司
地址：深圳市南山区粤海街道高新南四道高新技术工业村R1-A栋附3楼302

深圳市志达成网络科技有限公司
地址：深圳市南山区南山街道高新南四道高新技术工业村R1-A栋附3楼303

深圳市宏观网络科技有限公司
地址：深圳市南山区粤海街道高新南四道高新技术工业村R1-A栋附3楼301

深圳市科达唯网络科技有限公司
地址：深圳市南山区南山街道高新南四道高新技术工业村R1-A栋附3楼301-1

深圳市宏之美网络科技有限公司
地址：深圳市南山区粤海街道高新南四道高新技术工业村R1-A栋附3楼302


**以上都是同一家公司，实际存在的是 *志远弘业网络科技* 其他都是虚假的！！！**

**Comment by npcola** [comment]
超感谢提供这么多数据！！
待会我去提交

**Comment by starlight02** [comment]
又让我撞见了这家......

深圳市卓宏信息科技有限公司
深圳市南山区粤海街道高新南四道现代大厦R1-A-3楼301

深圳市科名文化传播有限公司
深圳市南山区粤海街道高新南四道现代大厦R1-A-3楼301-2

深圳市鸿平网络科技有限公司
深圳市南山区粤海街道高新南四道现代大厦R1-A-3楼301-3

**以上还是 *志远弘业网络科技*  的虚假公司**

<s>我找个工作容易吗我</s>

**Comment by npcola** [comment]
天呐,怎么这么多.我待会就提交
谢谢提供~
~~都不容易都不容易~~
