### ISSUE TITLE
深圳市神州通联科技有限公司是培训机构

### ISSUE THREAD

**Issue by xlzhu** [ZGWS88/TI#13]
地址：深圳市龙华区腾龙路(上塘地铁站A出口）淘金地大厦A座1301，这个地址注册了其他 5 家公司，都是为了发职位招聘

**Comment by npcola** [comment]
关于“深圳市神州通联科技有限公司”，稍晚会进行添加合并。
关于淘金地大厦1301楼层的公司，在数据里有了。
感谢提供数据。
