### ISSUE TITLE
深圳人人软件技术服务有限公司是达内的培训机构

### ISSUE THREAD

**Issue by WangXi01** [ZGWS88/TI#14]
地址：深圳龙华新区龙华街道和平东路金銮国际商务大厦7楼710

**Comment by npcola** [comment]
这家公司在天眼查查不到相关数据。暂不录入。谢谢。

**Comment by polo320** [comment]
他说的没错，这家公司的确是达内的培训机构

**Comment by npcola** [comment]
周末添加，谢谢反馈

**Comment by wangjixun** [comment]
19楼也是，在智联招聘可以搜索到达内过期的招聘

**Comment by npcola** [comment]
「深圳市人人软件有限公司」已改名为「深圳市翠园科技有限公司」。怪不得找不到。两家现已录入。
