### ISSUE TITLE
有几家不确定是不是培训，烦请确认下。

### ISSUE THREAD

**Issue by zzfgary** [ZGWS88/TI#15]
深圳神州讯盟软件有限公司
香港医博系统服务有限公司深圳代表处
深圳市思品信息技术有限公司
深圳市一德文化科技有限公司
深圳四方精创资讯股份有限公司
陕西九鼎通信技术有限公司

**Comment by npcola** [comment]
深圳神州讯盟软件有限公司，不像是
香港医博系统服务有限公司深圳代表处，不像是
深圳市思品信息技术有限公司，可能是
深圳市一德文化科技有限公司，教育行业，不像是
深圳四方精创资讯股份有限公司，不像是
陕西九鼎通信技术有限公司，不像是
（以上均属个人观点。有空多百度谷歌天眼查，如果是培训总会有相关资料的。以后自己动手查吧= =。

**Comment by zzfgary** [comment]
我也是查了很多网上的，不确定才发上来的。

**Comment by kid0100** [comment]
我也来加一个，深圳前海开南科技有限公司。
