### ISSUE TITLE
新发现一家深圳的培训机构

### ISSUE THREAD

**Issue by Chivasknight** [ZGWS88/TI#18]
新发现一家，智联上招聘的公司是 深圳市粤振鑫实业发展有限公司，通知的面试地点在 宝安区西乡坪洲地铁站D出口宝源路1053号资信达大厦4楼403。今天去了发现现场的公司名字叫睿思源，这个名字一搜索全是培训机构信息，问工作人员这两家公司之间什么关系，说都是XX公司分部（这个名字没记下来）。

**Comment by npcola** [comment]
名单已添加，下次更新可以看到。谢谢提供
~~应该是达内分部的吧。。我也不确定~~
