### ISSUE TITLE
找到几个培训公司

### ISSUE THREAD

**Issue by letaibai** [ZGWS88/TI#2]
名称:深圳市天之腾科技有限公司
地址:深圳市罗湖区大剧院f出口嘉宾花园A座四楼

名称:深圳市鲲鹏科技有限公司
地址:深圳市罗湖区大剧院f出口嘉宾花园A座四楼

名称:深圳市前海保百业互联科技有限公司
地址:深圳市罗湖区大剧院f出口嘉宾花园A座四楼

名称:深圳博为峰信息技术有限公司
地址:广东深圳福田华强北深南中路统建办公楼3栋6楼

名称:深圳晶城网络科技有限公司
地址:广东深圳福田华强北深南中路统建办公楼3栋6楼

**Comment by npcola** [comment]
已添加.谢谢
