### ISSUE TITLE
想添加一个培训公司

### ISSUE THREAD

**Issue by xuechaoke** [ZGWS88/TI#21]
好像是拿别的公司的名字在前程无忧上挂的名， 名字叫 中芯微智能有限公司
面试地点：深圳市龙岗区坂田坂雪岗大道百瑞达大厦 14楼 13A06室　

去到面试发现公司名不其实。 以你技术部好让你作为储备人员。时间是两个月。一个月补贴1000
但是要交押金6000元，还要签订一些违反劳动法的协议。 希望ZGWS88 有时间可以写上去。谢谢

**Comment by npcola** [comment]
已添加。谢谢提供。（好像回复慢了

**Comment by xuechaoke** [comment]
谢谢添加 。 祝你生活愉快

**Comment by starlight02** [comment]
这个我也碰到了，公司真名叫 **随记网络** ，我差点被忽悠进去
