### ISSUE TITLE
深圳骗人的培训机构增加

### ISSUE THREAD

**Issue by Jasonsmithcn** [ZGWS88/TI#24]
深圳果粒文化信息科技有限公司
深圳市龙华区龙华街道梅龙大道2229号政商中心4楼430/321/429
服务热线：0755-21030591

深圳果粒科技有限公司
深圳市龙华区龙华街道梅龙大道2229号政商中心4楼430/321/429
服务热线：0755-21030219

**Comment by npcola** [comment]
两家公司均为同一家。另“深圳超时空网络科技有限公司”是该法人的另一家公司。
都添加到名单里了。
非常感谢提供资料。
