### ISSUE TITLE
培训公司

### ISSUE THREAD

**Issue by wrongmoon** [ZGWS88/TI#25]
（深圳市卓宏信息科技有限公司）和名单里已有的（深圳市志远弘业网络科技有限公司）是同一家公司
公司地址：深圳市南山区粤海街道高新南四道R1-A现代大厦3楼301
![image](https://user-images.githubusercontent.com/24873136/42324487-f00614ea-8095-11e8-9065-a0d370e13f48.png)

**Comment by npcola** [comment]
名单已添加。这两天会更新

**Comment by npcola** [comment]
感谢提供
