### ISSUE TITLE
只知道公司地址，不知道公司具体名称

### ISSUE THREAD

**Issue by wrongmoon** [ZGWS88/TI#26]
地址：深圳市龙华新区和平路与东环一路交叉口汇海广场a座21楼。这家公司叫什么“人人科技”应该是达内的子公司什么的，
![image](https://user-images.githubusercontent.com/24873136/42324240-31f03706-8095-11e8-8890-229a30677ff5.png)

**Comment by npcola** [comment]
只有地址我也不好整理.
暂不添加.抱歉.
也谢谢提供相关信息.
