### ISSUE TITLE
报告一个疑似培训公司

### ISSUE THREAD

**Issue by RekiDunois** [ZGWS88/TI#27]
汇众传媒广州分公司
地址: 广州市天河区石牌西路KB展望数码广场13A层12室

这公司好像有个正经的汇众传媒主页, 但是你搜这个地址会发现那里其实是个动漫游戏培训基地, 发短信让我去面试需求携带身份证

**Comment by npcola** [comment]
汇众传媒广州分公司没怎么找到，不过找到可能是「汇众传媒」的母公司或子公司。稍后会更新列表。
感谢提供相关信息。
