### ISSUE TITLE
亲身经历，两家培训机构

### ISSUE THREAD

**Issue by iLovT** [ZGWS88/TI#29]
百分百为培训机构：理想智慧有限公司 （深圳市宝安西乡地铁站B出口盐田股份（汇潮科技大厦）15楼1508
  深圳市海斯特智能有限公司 （深圳市龙岗区坂田地铁C出口坂田中心大厦7楼708）

**Comment by npcola** [comment]
你说的应该是：「深圳市理想智荟软件有限公司」，该公司已添加到名单。
「深圳市海斯特智能有限公司」虽然在天眼查搜不到，但还是添加到名单吧。
非常感谢提供相关资料。
