### ISSUE TITLE
有两家疑似培训，麻烦确认一下，谢谢。

### ISSUE THREAD

**Issue by Funnyyanne** [ZGWS88/TI#32]
深圳市淑美达设计有限公司
深圳市善众网络科技有限公司

**Comment by npcola** [comment]
个人感觉：都是

**Comment by Funnyyanne** [comment]
还有一家叫科力康创意文化有限公司
去到发现是什么众成教育 询问后说是子公司，就觉得是培训机构没上去了(它有三个带走众成的公司名，看起来也像是)，避免浪费不必要的时间  地点是在宝安区宝安大道4708号龙基广场

**Comment by npcola** [comment]
应该是叫「深圳市众成智能科技有限公司」，我还查不到是不是它的子公司。还有一个名字叫「深圳市众智成电子商务有限公司」，第三个名字目前还查不到。
不过「深圳市科力康创意文化有限公司」我觉得是培训公司。
如果有误请指出，非常感谢。

**Comment by Funnyyanne** [comment]
好像是看到有这几个名字了，那个楼下招牌。
