### ISSUE TITLE
培训公司

### ISSUE THREAD

**Issue by keffSha** [ZGWS88/TI#33]
公司：广州六道信息科技有限公司。
地址：广州市天河区珠江东路30号广州银行大厦11楼

公司：华信科技
地址：广东省广州市天河区天平架陶庄路互联网生态家园5号空间2楼

**Comment by npcola** [comment]
已添加，稍后更新。
「华信科技」应该是「北京华信智原教育技术有限公司广州分公司」，名单已有
感谢提供相关信息
