### ISSUE TITLE
培训机构

### ISSUE THREAD

**Issue by puanduan** [ZGWS88/TI#35]
深圳云尚天贸易有限公司
Add:地址：深圳龙岗区左创智慧大厦501

深圳市朗倩实业发展有限公司
公司地址：宝安区西乡固戍地铁口A出口直行150米，绵商大厦6楼6058室（一楼华鼎盛酒店入）

感觉有问题，没去。第二个谁验验真假？

**Comment by npcola** [comment]
我觉得都有问题。
列表稍晚更新。
感谢提供
