### ISSUE TITLE
更新了一些相关信息及建议

### ISSUE THREAD

**Issue by hoochanlon** [ZGWS88/TI#37]
* 一个个的添加 还不如爬了天眼查与相关招聘网站的含有培训教育的信息；
* 看了下程序员找工作黑名单repo提到的公司 所侧重点并不是应届或新人找工作；
* 这次更新较多，merge pull request 一下

**Comment by npcola** [comment]
1. 我觉得并不是所有含有培训教育信息的机构都属于培训(~~骗子~~)机构，所有只有当遇上了或者查到了我才会去添加。
2. 并不是只有程序员才会遇到这些公司，其他职业也会遇到，我记得我的Readme里面也添加了其他公司黑名单链接。
3. 我先看看怎么merge🤦‍♂️（好久没用git了

**Comment by hoochanlon** [comment]
验证含有百分比里的少数；ps: icam，我支持你。
