### ISSUE TITLE
深圳培训机构-柯华创想科技有限公司

### ISSUE THREAD

**Issue by Famine-Life** [ZGWS88/TI#38]
**柯华创想科技有限公司**
这个公司，发面试邀请函，会使用：**深圳市创想科技有限公司**的字样。
石锤无误哦
**地址：**
深圳市宝安区翻身地铁站B出口金宝商务大厦6楼8605

**Comment by npcola** [comment]
已添加，稍晚更新列表。
感谢提供资料

**Comment by 969921476** [comment]
深圳柯华创想科技有限公司确定是培训机构吗？？？

**Comment by Famine-Life** [comment]
是的！我去过



---原始邮件---
发件人: "969921476"<notifications@github.com&gt;
发送时间: 2020年7月30日(周四) 中午11:13
收件人: "ZGWS88/TI"<TI@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"练涛"<xanwidtf@foxmail.com&gt;;
主题: Re: [ZGWS88/TI] 深圳培训机构-柯华创想科技有限公司 (#38)




 
深圳柯华创想科技有限公司确定是培训机构吗？？？
