### ISSUE TITLE
亲身经历，沈阳的一家培训机构

### ISSUE THREAD

**Issue by mrcongliu** [ZGWS88/TI#39]
两个月之前遇到的，现在貌似停止虚假招聘了。
这种情况要不要加到列表里？
公司名字有两个：
沈阳乾包互联网金融服务有限公司
沈阳乾包网络信息服务有限公司
地址：辽宁省沈阳市和平区三好街94-1号同方广场A座31层
谢谢大佬！

**Comment by npcola** [comment]
感谢提供资料。
稍晚更新列表。
