### ISSUE TITLE
看到深圳紫川在列表里，有疑问

### ISSUE THREAD

**Issue by Silencesnow** [ZGWS88/TI#4]
紫川是一家很大的外包公司的，不是培训机构，在列表里看到这个：

公司:深圳市紫川软件有限公司
地址:深圳市龙华新区腾龙路淘金地电子商务孵化大厦B座406

地址是不是正确的我不太清楚，不过紫川不是培训机构
ps感谢提供这个列表

**Comment by npcola** [comment]
可能我把「深圳市紫川软件有限公司」和「深圳市紫川互联信息有限公司」搞混了。后者才算是培训行列。我这就改过来
