### ISSUE TITLE
说下我遇到的一家培训公司的手段吧

### ISSUE THREAD

**Issue by LHR-lhr** [ZGWS88/TI#42]
地址：广州市天河区华夏路13号南岳大厦9楼901房
她发来的面试通知邮件写的是“**广州瑞普科技有限公司**”
但是地址却和天眼查的不一致而且天眼查上“**广州瑞普科技有限公司**”是[注销](https://www.tianyancha.com/company/3064005073)状态
所以搜了下地址发现这个地址对应的公司是“[**广州东方标准人才服务有限公司**](https://www.tianyancha.com/company/1615294123)”
而且我有个同学就是在这里培训的

**Comment by npcola** [comment]
感谢提供资料.抱歉最近有点忙,稍晚添加更新上去

**Comment by kanggou** [comment]
现在公司名已经改为**广州米瑞有限公司**
