### ISSUE TITLE
发一个培训机构

### ISSUE THREAD

**Issue by Dexilc** [ZGWS88/TI#43]
在前程无忧上公司名为深圳市鸿发盛科技有限公司，打着招助理的旗号，发短信通知面试的时候公司名又变成深圳鸿融发科技有限公司，本来都有些怀疑了，毕竟以前培训过，到目的地后的公司名又不一样，可惜没记住，还好地址记住了
地址：深圳福田区多丽国家电子商务示范基地1号楼310X(具体几室记不清了，反正很明显可以看到有一个房间坐了一批人在学）

**Comment by npcola** [comment]
感谢提供资料.抱歉最近有点忙,稍晚添加更新上去
应该是"深圳市融会通网络科技有限公司",地址是"深圳市福田区梅林街道梅华路105号多丽工业园（福田国际电子商务产业园）1栋712".
1号楼310x的公司暂时找不到

**Comment by Dexilc** [comment]
没什么抱歉的，都只是义务劳动，让大家少走冤枉路而已，刚才特地在前程无忧的网站上看了，你确认的地址是正确的，职位都已经点了举报，还没给下架，前程无忧也是一丘之貉
