### ISSUE TITLE
今天发现一个疑似培训机构的公司

### ISSUE THREAD

**Issue by xiaJue** [ZGWS88/TI#6]
公司:玖易创新网络科技有限公司
地址:深圳市龙华新区地铁四号线清湖地铁站A出口直行第一个路口右转300米大唐时代大厦B座12楼

PS:收到电话。但我并未投递。智联
前程无忧和拉钩都搜不到这个公司。从电话中听出来比较可疑。(做助理，无经验，问我想干哪方面等+周末面试)网上搜索发现该公司名是北京的，而我在深圳。据去过的网友说是到了地址上位置根本不是这个公司。应该可以确定是培训机构了。

**Comment by npcola** [comment]
这个公司确实是属于培训机构.
名单已经添加.非常感谢提供情报

**Comment by cropflre** [comment]
广东粤为信息科技有限公司也是培训机构。

**Comment by npcola** [comment]
已添加,谢谢
